Fix cross-shell to support new configuration style
Signed-off-by: Wartan Hachaturow <wart@slind.org>

diff --git a/cross-shell b/cross-shell
--- a/cross-shell
+++ b/cross-shell
@@ -1,45 +1,51 @@
 #!/bin/sh
 #
 # This tool is a piece of evil magic, which allows one to cross-bootstrap
-# target userlands inside of Slind development chroot.
+# target userlands inside of Slind development chroot. Invocation format is:
 #
-# There is a generic problem with bootstrapping when target != host
-# architecture - some tools binary utilities are executed during packages
-# installation. cross-shell allows to overcome this problem, by using
-# LD_PRELOAD approach. Special Slind target rootfs is created with
-# host == target and calls to binary utilities during bootstrapping are
-# intercepted and executed in this specially created rootfs.
+#   slind-shell command arch command_args
 #
 # The following commands are provided for cross-shell user:
-#
 # bs
 #   Bootstrap target rootfs inside of development chroot
-#
 # sh
-#   Execute single command in context of target rootfs
-#
+#   Execute single command in context of target rootfs, command_args is
+#   the command to be executed
 # apt
-#   Run "apt-get update; apt-get install $*; apt-get clean" for target
-#
+#   Run "apt-get update; apt-get install $*; apt-get clean" for target,
+#   command_args is list of packages to install
 # pack
 #   Create a tar image of your target root filesystem
+#
+# NOTE: There is a generic problem with bootstrapping when target != host
+# architecture - some binary utilities are executed during packages
+# installation. cross-shell allows to overcome this problem, by using
+# LD_PRELOAD approach. Slind rootfs is created with host == target and calls
+# to binary utilities during bootstrapping are intercepted and executed in
+# this special rootfs.
 #
 
 #set -x
 
-CONF_GLOBAL=/etc/cross-shell.conf
-CONF_LOCAL=~/.cross-shell
-if [ -f $CONF_LOCAL ]; then
-	. $CONF_LOCAL
+LIBUTILS=/usr/lib/slind-core/libutils.sh
+if [ -f "$LIBUTILS" ]; then
+        . $LIBUTILS
 else
-	if [ -f $CONF_GLOBAL ]; then
-		. $CONF_GLOBAL
-	else
-		echo "Cannot find any configuration file, exiting."
-		exit 1
-	fi
+        echo "Error: can't load library $LIBUTILS"
+        exit 1
 fi
 
+FSTAB=`conf_get_var_relaxed $SLIND_DEF_CONFIG cross-shell chr_tgt_fstab`
+INITTAB=`conf_get_var_relaxed $SLIND_DEF_CONFIG cross-shell chr_tgt_inittab`
+HN=`conf_get_var_strict $SLIND_DEF_CONFIG cross-shell tgt_hostname`
+OUTPUTDIR=`conf_get_var_strict $SLIND_DEF_CONFIG cross-shell chr_tgt_image_dir`
+SUITE=`conf_get_var_strict $SLIND_DEF_CONFIG common slind_suite`
+REPO=`conf_get_var_strict $SLIND_DEF_CONFIG common slind_mirror`
+
+HOSTARCH=`dpkg --print-architecture`
+ARCH="$2"
+WHERE=/rootfs-$ARCH
+FAKECHROOT_CROSS=/rootfs-$HOSTARCH
 DEBOOTSTRAP=/usr/sbin/debootstrap
 BASEDIR=`pwd`
 CROSS_ARCH=$ARCH
@@ -67,16 +73,20 @@ case "$1" in
 		echo "deb $REPO $SUITE core" > $WHERE/etc/apt/sources.list
 		echo "APT::Architecture \"$ARCH\";" > $WHERE/etc/apt/apt.conf
 		# configure target
-		echo "# THIS IS DUMMY FSTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/fstab
-		echo "slind" > $WHERE/etc/hostname
+		if [ -f "$FSTAB" ]; then
+			cat $FSTAB $WHERE/etc/fstab;
+		else
+			echo "# THIS IS DUMMY FSTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/fstab
+		fi
+		echo "$HN" > $WHERE/etc/hostname
 		;;
 	sh)
-		shift
+		shift; shift;
 		_cmd="$*"
 		$FAKECHROOT_CROSS/bin/busybox chroot $WHERE $_cmd
 		;;
 	apt)
-		shift;
+		shift; shift;
 		_pkglist="$*"
 		$FAKECHROOT_CROSS/bin/busybox chroot $WHERE /usr/bin/apt-get update
 		$FAKECHROOT_CROSS/bin/busybox chroot $WHERE /usr/bin/apt-get install --yes --force-yes $_pkglist
@@ -84,13 +94,23 @@ case "$1" in
 		;;
 	pack)
 		unset LD_PRELOAD
-		echo "# THIS IS DUMMY FSTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/fstab
-		echo "# THIS IS DUMMY INITTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/inittab
-		echo "slind" > $WHERE/etc/hostname
+		# Create target fstab
+		if [ -f "$FSTAB" ]; then
+			cat $FSTAB $WHERE/etc/fstab;
+		else
+			echo "# THIS IS DUMMY FSTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/fstab
+		fi
+		# Create target inittab
+		if [ -f "$INITTAB" ]; then
+			cat $INITTAB $WHERE/etc/inittab;
+		else
+			echo "# THIS IS DUMMY INITTAB GENERATED BY cross-shell FOR YOU" > $WHERE/etc/inittab
+		fi
+		echo "$HN" > $WHERE/etc/hostname
 		
 		# pack things
 		( cd $WHERE; \
-			tar cf /rootfs-$ARCH.tar \
+			tar cf $OUTPUTDIR/rootfs-$ARCH.tar \
 				--exclude=debootstrap \
 				--exclude=repo \
 				--exclude=proc \
